### ISSUE TITLE
Motion model (DDMR, Ackermann, Holonomic)

### ISSUE THREAD

**Issue by Geonhee-LEE** [Geonhee-LEE/mpc_ros#14]
- [ ] Add and separate the Motion model (DDMR, Ackermann) for generalization

**Comment by roboticlemon** [comment]
Hi @Geonhee-LEE did you make any internal progress on this? I am very interested in an Ackermann motion model and also a 4 Wheel Independent steer like model (holonomic like motion). 

Great work so far!

**Comment by Geonhee-LEE** [comment]
@ingramator  Hi, thanks for interesting!
I planned to control various model in order to use model predictive control. The Ackermann model has many type, which include front steering and rear steering, etc. Our target model is front steering once, we want to extend it later. Would you recommend the model type you think with images or reference link?

**Comment by roboticlemon** [comment]
@Geonhee-LEE This sounds very good! Definitely start with front steering ackermann (like a car). 

<img src="https://user-images.githubusercontent.com/2769347/107349900-df078380-6b1c-11eb-8469-24bc6dc82e58.png" width="150">
My team can potentially help with rear-stear ackermann and dual-ackermann. 

Here is a picture of 4 wheel independent steer:
<img src="https://user-images.githubusercontent.com/2769347/107350259-52a99080-6b1d-11eb-81e8-7fd09411f5bc.png" width="150">

[4 Wheel Independent Steer model kinematics.](https://digital-library.theiet.org/docserver/fulltext/joe/2015/1/JOE.2014.0241.pdf?expires=1612866414&id=id&accname=guest&checksum=A25F61DABC7C038A7B1B40517DE33F75)

An example of 1 wheel in action [[Youtube](https://www.youtube.com/watch?v=IUnAn8NEyjU)]. Let me know if you have any questions :+1:

**Comment by Geonhee-LEE** [comment]
@ingramator  Great! Your model is attractive but it seems like more complex model than simple car model. I will try this model if will take a opportunity. Antyway, feel free to make a PRs including a new model if you are interested in `mpc_ros` improvements.
