### ISSUE TITLE
Use mpr_ros with a different Robot model

### ISSUE THREAD

**Issue by mrm20** [Geonhee-LEE/mpc_ros#15]
Hi, would be possible to use this mpc package with another differential drive robot model? I'd need to use it for my model with the libgazebo_ros_diff_drive.so plugin, so I wonder if I could change the servingbot model for it.

**Comment by Geonhee-LEE** [comment]
@mrm20  

Hi, this repository supports the DDMR you said to control with MPC. You can also change the other DDMR model via model changes .

**Comment by mrm20** [comment]
Thanks!!
