### ISSUE TITLE
Information about mpc parameters

### ISSUE THREAD

**Issue by mjestebang** [Geonhee-LEE/mpc_ros#16]
Hello, Geonhee 

I would like to get information about the parameters you use in the scripts in the "param" folder for the epitrochoid, square.... Because I am trying to adapt it to my own robot and to modify them I would like to understand them. 
If you could provide me with any documentation on them I would appreciate it. 

Thank you, best regards.

**Comment by Geonhee-LEE** [comment]
@mjestebang 
Sorry for that. I haven't arranged the parameters. I will provide the param info and topic later. If you want to contribute the `mpc_ros` improvement, please create the new branch and make a PR.
