### ISSUE TITLE
TF error

### ISSUE THREAD

**Issue by ZyHuang97** [Geonhee-LEE/mpc_ros#21]
Thanks for your code.
I tried to reimplement it, but the robot didn't move at all. 
It seems like a tf problem. Could you give me any advice?

Timed out waiting for transform from base_link to map to become available before running costmap, tf error: canTransform: target_frame map does not exist. canTransform: source_frame base_link does not exist.. canTransform returned after 98.075 timeout was 0.1.

Thanks and regards.

**Comment by Geonhee-LEE** [comment]
HI, @ZyHuang97. Thanks for interesting this package. Did you install `map_server` of ros?

**Comment by aakashs0ni** [comment]
Hi, @Geonhee-LEE. I have a similar issue. I have installed map_server. Furthermore, I have robot model error in Rviz. It says No transform from [base_link, body_link, lidar_link...] to [map].

**Comment by Geonhee-LEE** [comment]
@ZyHuang97  @aakashs0ni  Hello, Did you install the `robot_state_publisher` also?
Otherwise, let me know the detailed situation such as launch name, error logs, etc.

**Comment by wangpeihu** [comment]
@Geonhee-LEE Hello,Thank you for the code.I have run the code ,but broke into some trouble.I have installed map_server and robot_state_publisher,but still can't make it,the robot didn't move.Could you please give me some advice?Thanks

**Comment by wangpeihu** [comment]
![mpc_tf](https://user-images.githubusercontent.com/51895450/118267563-db561500-b4ee-11eb-8c4f-8dba5321f5d1.png)
![mpc_rqt_graph](https://user-images.githubusercontent.com/51895450/118267566-ddb86f00-b4ee-11eb-8441-fa6e2f471801.png)
![log_error_1](https://user-images.githubusercontent.com/51895450/118267572-df823280-b4ee-11eb-9b2b-1588370d9700.png)
![log_error_2](https://user-images.githubusercontent.com/51895450/118267578-e1e48c80-b4ee-11eb-80a5-89b9bcf1b2e6.png)
![rviz_err_1](https://user-images.githubusercontent.com/51895450/118267582-e446e680-b4ee-11eb-9c23-715b4525df1a.png)
![rviz_err_2](https://user-images.githubusercontent.com/51895450/118267583-e4df7d00-b4ee-11eb-9f45-d3e4633caa8c.png)

**Comment by wangpeihu** [comment]
![mpc_tf](https://user-images.githubusercontent.com/51895450/118267692-0c364a00-b4ef-11eb-8203-cf8bf2f78a96.png)
![mpc_rqt_graph](https://user-images.githubusercontent.com/51895450/118267695-0e000d80-b4ef-11eb-9dc1-51e039340bca.png)
![log_error_1](https://user-images.githubusercontent.com/51895450/118267699-0f313a80-b4ef-11eb-8027-88b3fd622cd2.png)
![log_error_2](https://user-images.githubusercontent.com/51895450/118267702-11939480-b4ef-11eb-999e-f8ebe48ccb1a.png)
![rviz_err_1](https://user-images.githubusercontent.com/51895450/118267711-135d5800-b4ef-11eb-8373-164903720300.png)
![rviz_errpr_2](https://user-images.githubusercontent.com/51895450/118268344-db0a4980-b4ef-11eb-89b9-f0c604d5f1b4.png)

**Comment by wangpeihu** [comment]
![rviz_errpr_2](https://user-images.githubusercontent.com/51895450/118267983-60d9c500-b4ef-11eb-8d53-5c743a83a13a.png)

**Comment by Geonhee-LEE** [comment]
Hi @aakashs0ni where is the odom tf and odom topic? If you want to run, the odom tf and odom topic are necessary.

**Comment by gft-ai** [comment]
Hi, I am facing the same issue. How and where do you publish those topics from? Do I need to write a separate script for them?

**Comment by gft-ai** [comment]
> Hi, I am facing the same issue. How and where do you publish those topics from? Do I need to write a separate script for them?

Found the problem. I was missing

`ros-melodic-gazebo-plugins`
