### ISSUE TITLE
ROS2 implementation timeline 

### ISSUE THREAD

**Issue by gft-ai** [Geonhee-LEE/mpc_ros#27]
Hi, great work. Just managed to get it to work on my machine in a docker container.

I saw you have planned to implement your work in ROS2 and just wanted to ask what the progress on that is?

Thank you!

**Comment by Geonhee-LEE** [comment]
Hi, @gft-ai !
Thanks for your attention. I plan to learn ROS2 next month. After achieving ROS2 implementation experiences, I will focus on ROS2 implementation next year. If anyone helps our repo, it can finish early.
