### ISSUE TITLE
csv 

### ISSUE THREAD

**Issue by ChengYe9527** [Geonhee-LEE/mpc_ros#28]
Hello,I have some questions:
I read the source code, there is a csv file loaded in it, and how does cte and eteta get in the csv file?

thanks！

**Comment by Geonhee-LEE** [comment]
Hi, @ChengYe9527 You can easily find the contents with keyword 'csv'. I found the writing function at https://github.com/Geonhee-LEE/mpc_ros/blob/934711d128117ead6fcde21561d80809ab1a82b4/mpc_ros/src/navMPCNode.cpp#L443
