### ISSUE TITLE
Applicable to ackermann or bicycle model without leaning dynamics?

### ISSUE THREAD

**Issue by bxc237** [Geonhee-LEE/mpc_ros#29]
Hi, I would like to know if this planner can work on Ackermann or bicycle model without leaning dynamics? I notice that there are "kinetic branch" that has a lot of code about Ackermann and also a "bicycle_modeling branch". Thank you!

**Comment by Geonhee-LEE** [comment]
@bxc237 I recommend that you refer to the 'bicycle_modeling' branch.

**Comment by bxc237** [comment]
Thank you. Close issue.
