### ISSUE TITLE
how to change model

### ISSUE THREAD

**Issue by JingtaoHe** [Geonhee-LEE/mpc_ros#32]
I have gotten the ackermann model and I  want to know how to replace the diff model in the servingbot ,in other words,what orders I should change in the bag.
thanks for your help!

**Comment by Geonhee-LEE** [comment]
> I have gotten the ackermann model and I want to know how to replace the diff model in the servingbot ,in other words,what orders I should change in the bag. thanks for your help!

DDMR type is default. I supports the various model in https://github.com/Geonhee-LEE/mpc_ros_description repository. However, I'm sorry that stopped the development for ackermman model.
