### ISSUE TITLE
How to make a simulation with dwa?

### ISSUE THREAD

**Issue by liunini123** [Geonhee-LEE/mpc_ros#33]
Hi, I want to compare the simulation results of MPC and DWA. 

I completed the simulation with MPC, like this:
![lALPDgtYz8IdYAfNAa7NAzY_822_430](https://user-images.githubusercontent.com/70358354/155144093-6ef28f32-193a-460d-a606-a6360cbb3985.png)

But I don't know how to make a simulation with DWA, like the right results in this picture.
![lQLPDhssxXjbX1DNAg7NBJCwvNaNuUn4k_wCGgbQ4EC9AA_1168_526](https://user-images.githubusercontent.com/70358354/155142935-0351d885-043c-4d88-af6f-841aaa281c43.png)

**Comment by Geonhee-LEE** [comment]
Hi, @liunini123 
Actually, you should launch the [dwa_local_planner](http://wiki.ros.org/dwa_local_planner?distro=noetic) in order to use DWA . This repo also supports [dummy global_planner plugin](https://github.com/Geonhee-LEE/mpc_ros/blob/melodic/mpc_ros/global_planner_plugin.xml). Could you refer to above link?

**Comment by liunini123** [comment]
I have downloaded the navigation package and add some codes in ref_trajectory_tracking_gazebo.launch.
![image](https://user-images.githubusercontent.com/70358354/155259238-f18d61ab-c77e-4493-a9f4-ef4902938238.png)

But the robot didn't move. And the terminal shows like: 
![image](https://user-images.githubusercontent.com/70358354/155259117-ed0771ec-27a2-4d30-a031-6b8c527cad70.png)

Can you tell me in detail how to start move_base  in the ref_trajectory_tracking_gazebo.launch. And choose DWA as the local planner?

**Comment by liunini123** [comment]
Another problem is when I run "roslaunch mpc_ros mpc_local_planner.launch  controller:=dwa", the robot always turn right, didn't follow the path.

https://user-images.githubusercontent.com/70358354/155269681-5c09cb39-a39c-4223-babe-d181ae51cc0f.mp4

**Comment by Geonhee-LEE** [comment]
Hi, @liunini123 

Did you change global planner with `GeonPlanner`? In order to deliver path from `dwa_trajectory_generation.py` to global planner, you should use `GeonPlanner` not Global Planner

**Comment by Geonhee-LEE** [comment]
> mpc_local_planner

To get nice DWA performance, parameter tuning is necessary. Why don't you try to change the dwa params?

**Comment by liunini123** [comment]
> Hi, @liunini123
> 
> Did you change global planner with `GeonPlanner`? In order to deliver path from `dwa_trajectory_generation.py` to global planner, you should use `GeonPlanner` not Global Planner

I changed the global planner with 'GeonPlanner', then the robot can move. Sometimes,  the robot stop moving because path.cost_ < 0  in DWAPlannerROS. 
![image](https://user-images.githubusercontent.com/70358354/155880228-98b970da-fdba-400e-8480-8bd74baea186.png)
![image](https://user-images.githubusercontent.com/70358354/155880248-589dc784-5b4a-4a60-a5ed-b4f94efa2612.png)

https://user-images.githubusercontent.com/70358354/155880373-18d075ea-3e69-4615-9d8d-8437ed57f72b.mp4

**Comment by liunini123** [comment]
When I use dwa, global path is displayed in red and local path is displayed in blue in this video. The recorded path is far from global path sometimes. What should I do to make local path near to global path?

https://user-images.githubusercontent.com/70358354/156103323-3feefe12-4023-4a96-b953-ea4ddbfe4068.mp4

**Comment by Geonhee-LEE** [comment]
> When I use dwa, global path is displayed in red and local path is displayed in blue in this video. The recorded path is far from global path sometimes. What should I do to make local path near to global path?
> 
>  dwa1.mp4

Hi, @liunini123. In order to follow the every poses of geometry shape's path , it should cut with particular interval as local plan. As I remind,  `_pathLength` of [global path planner plugin](https://github.com/Geonhee-LEE/mpc_ros/blob/melodic/mpc_ros/src/global_planner/global_planner.cpp) corresponds that I mentioned above. 
If you want to make better conversion from global to local, I recommend that you consider path's sequence and distance.

**Comment by liunini123** [comment]
> 

Ok, Thank you! This video is played with dwa.

https://user-images.githubusercontent.com/70358354/156136220-50b83423-61c5-497c-9869-82973b93407a.mp4

**Comment by Geonhee-LEE** [comment]
@liunini123, you're welcome!
Actually, DWA is not a path tracking method but collision avoidance method. Therefore, DWA can't not help avoiding performance decrease in a path tracking experiment. I suggest the pure pursuit and Stanley method can be better control groups about MPC.
Finally, please close with comment if you finished your issue.
