### ISSUE TITLE
How to adopt the framework to my own kinematic robot model?

### ISSUE THREAD

**Issue by ghost** [Geonhee-LEE/mpc_ros#4]
Hi, thank you very much for sharing this library!
I was wondering what would I need to change in order to make it work with my custom car-like (Ackerman) robot?
Is there some kind of a doc/wiki/pdf for this?

Thank you!

**Comment by Geonhee-LEE** [comment]
Hi, this repo is for differential drive mobile robot. 
Why don't u refer to HyphaROS MPC MiniCar(https://hypharosworkshop.wordpress.com/)? 
It is based on Ackerman steering model.

Thanks.
