### ISSUE TITLE
Replacement solver

### ISSUE THREAD

**Issue by zrd1234** [Geonhee-LEE/mpc_ros#40]
Hello, the ipopt solver seems to be unable to work under the arm architecture. May I ask what part of work should be done if you want to change the solution? Thank you.

**Comment by Geonhee-LEE** [comment]
I recommend the optimization solver with CasADi, ACADOS in order to solve the MPC problem .

**Comment by zrd1234** [comment]
Hello, do I just need to replace trackRefTraj.cpp with ipopt?

**Comment by Geonhee-LEE** [comment]
@zrd1234 I think it is not easy to replace it. Because each solver's interface may be different such as Eigen, Vector, self-structured.

**Comment by zrd1234** [comment]
> @zrd1234 I think it is not easy to replace it. Because each solver's interface may be different such as Eigen, Vector, self-structured.

Hello, I'm really sorry. If you are free, could you upload and modify the code of the solver? Thank you very much.
