### ISSUE TITLE
An error is reported when the package is running, and the path cannot be followed

### ISSUE THREAD

**Issue by leigetiwen** [Geonhee-LEE/mpc_ros#7]
hello ,I ran this package and encountered some errors 。Terminal display this:
-----------------------------------------------
cost_cte, etheta, velocity: -nan, -nan, 10000
cost of actuators: -nan
cost of gap: -nan
------------ Total Cost(solution): 0------------

**Comment by Geonhee-LEE** [comment]
@leigetiwen 
Hi, let me know the exact situation? that error seems like abnormal calculation b/w path and robot

**Comment by leigetiwen** [comment]
@Geonhee-LEE I just publish a path and then report this error.so  I want to know what is required for a fixed path？

**Comment by Geonhee-LEE** [comment]
@leigetiwen I made the python file [python file](https://github.com/Geonhee-LEE/mpc_ros/blob/melodic/mpc_ros/script/mpc_trajectory_generation.py) to create fixed path. please refer to `generation_desired_path` function

**Comment by leigetiwen** [comment]
Okay， thank you
