### ISSUE TITLE
Cannot launch node

### ISSUE THREAD

**Issue by mjestebang** [Geonhee-LEE/mpc_ros#8]
Hello,
We are a group of robotic engineering students from Spain.

We are developing a project related to the model predictive control

We have implemented the "servingbot" model following all the steps indicated. We have installed ubuntu 18.04 together with ROS Melodic, we have installed the dependencies of ROS, IPOPT and cloned the repositories in our own catkin.

After that, We get errors when launching some nodes. Attached is a screenshot:

When launching mpc_ros nav_gazebo.launch 
I have an error:

cannot launch node of type [mpc_ros/nav_mpc]: Cannot locate node of type [nav_mpc] in package [mpc_ros]. Make sure file exists in package path and permission is set to executable (chmod +x)
When I try to search for the mpc_ros file in my directory I can't find it.

When launching roslaunch mpc_ros ref_trajectory_tracking_gazebo.launch 
I have an error:

cannot launch node of type [mpc_ros/tracking_reference_trajectory]: Cannot locate node of type [tracking_reference_trajectory] in package [mpc_ros]. Make sure file exists in package path and permission is set to executable (chmod +x)
This file also does not exist in my directory

The question is: Do I have to create those files? If so, how do I do it?
How can I reference the robot? 

I await your response, anything could be helpful.

Thank you so much.

**Comment by Geonhee-LEE** [comment]
Hello, @mjestebang 
I wonder why these error break. Could you check `catkin_make` the `bashrc` again?
